task: Cifar100Fed
synthesizer: Pattern
trigger: tri1_2x2
neurotoxin: False
invert: True

batch_size: 64
test_batch_size: 100
lr: 0.001
momentum: 0.9
decay: 0.0005
epochs: 2000
save_on_epochs: []
optimizer: SGD
log_interval: 100

pretrained: False

scheduler: True

poisoning_proportion: 0.4
backdoor_label: 0

# resume_model: model_Cifar100Fed_cifar100_benign\model_last.pt.tar.best
resume_model: model_Cifar100Fed_Jun.01_11.18.03_cifar100_tri1_2x2_clients_10_scale_5/model_last.pt.tar
# resume_model: saved_models/model_Cifar100Fed_May.29_13.40.58_cifar100_tri1_3x3_t0_scale_3/model_last.pt.tar
# resume_model: saved_models/model_Cifar100Fed_May.29_16.55.39_cifar100_tri1_5x5_t0_scale_3/model_last.pt.tar
# resume_model: 


loss_balance: MGDA
mgda_normalize: none

save_model: True
log: True
tb: True
report_train_loss: False

transform_train: True

fl: True
fl_no_models: 5
fl_local_epochs: 2
fl_adv_local_epochs: 5
fl_total_participants: 10
fl_eta: 2
fl_sample_dirichlet: False
fl_dirichlet_alpha: None
fl_diff_privacy:  False
fl_dp_clip: None
fl_dp_noise: None

fl_number_of_adversaries: 2
fl_weight_scale: 2
#fl_single_epoch_attack: 1


loss_tasks:
  - backdoor
  - normal
#  - nc_adv
#  - ewc
#  - latent
#  - latent_fixed


#poison_images_test:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588
#
#poison_images:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588