task: CifarFed
synthesizer: DBA
trigger: tri3_4x1x4_gap2
neurotoxin: False
clipping: False
clipping_norm: 30
invert: False

batch_size: 64
test_batch_size: 100
lr: 0.01
poison_lr: 0.005
momentum: 0.9
decay: 0.0005
epochs: 350
save_on_epochs: []
optimizer: SGD
log_interval: 100

pretrained: False

scheduler: True

poisoning_proportion: 0.1
backdoor_label: 0

resume_model: model_CifarFed_May.31_10.37.26_cifar10_benign/model_last.pt.tar
# resume_model: model_CifarFed_Jun.09_12.44.07_cifar10_benign_v2/model_last.pt.tar
# resume_model: model_CifarFed_Jun.09_13.55.11_cifar10_v2_howto_tri1_3x3_scale_2_adv_5_save_per10/model_last.pt.tar
# resume_model: /home/bei_chen/backdoors101/teacher/cifar10/howto/tri1_2x2/cifar10-resnet18.pt
# resume_model: /home/bei_chen/backdoors101/teacher/cifar10/howto/tri1_3x3/cifar10-resnet18.pt
# resume_model: /home/bei_chen/backdoors101/teacher/cifar10/howto/tri1_5x5/cifar10-resnet18.pt
# resume_model: /home/bei_chen/backdoors101/teacher/cifar10/neurotoxin/tri1_2x2/cifar10-resnet18.pt
# resume_model: /home/bei_chen/backdoors101/teacher/cifar10/neurotoxin/tri1_3x3/cifar10-resnet18.pt
# resume_model: /home/bei_chen/backdoors101/teacher/cifar10/neurotoxin/tri1_5x5/cifar10-resnet18.pt
# resume_model: /home/bei_chen/backdoors101/teacher/cifar10/DBA/tri2_1x4_gap2/cifar10-resnet18.pt
# resume_model: /home/bei_chen/backdoors101/teacher/cifar10/DBA/tri2_2x4_gap2/cifar10-resnet18.pt
# resume_model: /home/bei_chen/backdoors101/teacher/cifar10/DBA/tri2_1x4_gap24/cifar10-resnet18.pt
# resume_model: /home/bei_chen/DHBE-main/train_howto_cifar10_resnet18_tri1_3x3_sacle_2_e270/DHBE_train_adjlr0_e_2000_ps_5_wama_0.1_wd1_0.1_wtvl2_0.0001_wreal_0.1_wft_0.01_wadv_0.1_wcon_0.1_lrs_0.1_lrg_0.001_lrgp_0.001_results/student/cifar10-resnet18_epoch_2000.pt
# resume_model: /home/bei_chen/DHBE-main/train_howto_cifar10_resnet18_tri1_3x3_scale_2_e290/DHBE_train_adjlr0_e_2000_ps_5_wama_0.1_wd1_0.1_wtvl2_0.0001_wreal_0.1_wft_0.01_wadv_0.1_wcon_0.1_lrs_0.1_lrg_0.001_lrgp_0.001_results/student/cifar10-resnet18_epoch_2000.pt
# resume_model: /home/bei_chen/DHBE-main/train_howto_cifar10_resnet18_tri1_3x3_scale_2_e310/DHBE_train_adjlr0_e_2000_ps_5_wama_0.1_wd1_0.1_wtvl2_0.0001_wreal_0.1_wft_0.01_wadv_0.1_wcon_0.1_lrs_0.1_lrg_0.001_lrgp_0.001_results/student/cifar10-resnet18_epoch_2000.pt

loss_balance: MGDA
mgda_normalize: none

save_model: True
log: True
tb: True
report_train_loss: False

transform_train: True

fl: True
fl_no_models: 10
fl_local_epochs: 2
fl_adv_local_epochs: 5
fl_total_participants: 20
fl_eta: 2
fl_sample_dirichlet: False
fl_dirichlet_alpha: None
fl_diff_privacy:  False
fl_dp_clip: None
fl_dp_noise: None

fl_number_of_adversaries: 4
fl_weight_scale: 3
start_poison_epoch: 250
#fl_single_epoch_attack: 1


loss_tasks:
  - backdoor
  - normal
#  - nc_adv
#  - ewc
#  - latent
#  - latent_fixed


#poison_images_test:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588
#
#poison_images:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588