task: CifarFed
random_seed: 0
synthesizer: Pattern
trigger: tri1_3x3
neurotoxin: False
defense: robustlr
clipping_norm: 32

batch_size: 64
test_batch_size: 100
lr: 0.01
poison_lr: 0.005
momentum: 0.9
decay: 0.0005
epochs: 200
save_on_epochs: [49, 99]
optimizer: SGD
log_interval: 100

# scheduler: True

poisoning_proportion: 0.1
backdoor_label: 0

# resume_model: model_CifarFed_May.31_10.37.26_cifar10_benign/model_last.pt.tar
# resume_model: model_CifarFed_Oct.20_03.04.46_cifar10_tri1_3x3_defense_fedavg/model_last.pt.tar.epoch_199

loss_balance: MGDA
mgda_normalize: none

save_model: True
log: True
tb: True
report_train_loss: False

transform_train: True

fl: True
fl_no_models: 10
fl_local_epochs: 2
fl_adv_local_epochs: 5
fl_total_participants: 20
fl_eta: 2
fl_sample_dirichlet: False
fl_dirichlet_alpha: None
fl_diff_privacy:  False
fl_dp_clip: None
fl_dp_noise: None

fl_number_of_adversaries: 4
fl_weight_scale: 3
start_poison_epoch: 50
#fl_single_epoch_attack: 1


loss_tasks:
  - backdoor
  - normal
#  - nc_adv
#  - ewc
#  - latent
#  - latent_fixed