task: MNISTFed
synthesizer: Pattern
trigger: tri4_2x2
neurotoxin: False
clipping: False
clipping_norm: 30
invert: False

batch_size: 64
test_batch_size: 100
lr: 0.1
poison_lr: 0.05
momentum: 0.9
decay: 0.0005
epochs: 120
save_on_epochs: []
optimizer: SGD
log_interval: 100

pretrained: False

scheduler: True

poisoning_proportion: 0.4
backdoor_label: 0

# resume_model: 'model_MNISTFed_Oct.14_03.43.43_mnist_tri4_3x3/model_last.pt.tar'


loss_balance: MGDA
mgda_normalize: none

save_model: True
log: True
tb: True
report_train_loss: False

transform_train: True

fl: True
fl_no_models: 10
fl_local_epochs: 1
fl_adv_local_epochs: 10
fl_total_participants: 20
fl_eta: 2
fl_sample_dirichlet: False
fl_dirichlet_alpha: None
fl_diff_privacy:  False
fl_dp_clip: None
fl_dp_noise: None

fl_number_of_adversaries: 4
fl_weight_scale: 3
start_poison_epoch: 5
#fl_single_epoch_attack: 1


loss_tasks:
  - backdoor
  - normal
#  - nc_adv
#  - ewc
#  - latent
#  - latent_fixed

