task: TinyImageNet
synthesizer: Pattern
trigger: tri1_3x3

batch_size: 64
test_batch_size: 100
lr: 0.01
momentum: 0.9
decay: 0.0005
epochs: 50
save_on_epochs: []
optimizer: SGD
log_interval: 100

pretrained: False

loss_threshold: 1.0

# scheduler: ReduceLROnPlateau
scheduler: CosineAnnealingLR
# scheduler: MultiStepLR
# scheduler_milestones: [10, 40]

poisoning_proportion: 0.1
backdoor_label: 8
backdoor: False

loss_balance: MGDA
mgda_normalize: loss+

save_model: True
log: True
tb: True

transform_train: True


loss_tasks:
  - backdoor
  - normal
#  - neural_cleanse
#  - sentinet_evasion


